### ISSUE TITLE
No GUI when running python scripts/train.py --env stack

### ISSUE THREAD

**Issue by LeiHHHuang** [UT-Austin-RPL/maple#4]
Hi there! When I run `python scripts/train.py --env stack`, there is no visualization of MuJoCo GUI and the screenshot below is what's in the terminal. I was wondering if this is expected? Are there any ways that I can display the GUI? Thanks a lot in advance! 
![Screenshot from 2022-07-20 11-18-25](https://user-images.githubusercontent.com/43896717/180055064-6cbddbf5-ff67-44fb-b39b-27f7b7cbb5e0.png)

**Comment by snasiriany** [comment]
Hi Lei, thank you for the question. Indeed this is expected, however we offer the choice to render offscreen videos and save them. It seems you have the `"save_video"` feature turned on, which exactly does this. You can set specific settings in `"save_video_period"` and `"dump_video_kwargs"`. Feel free to play with these features to find the setting you are looking for.

**Comment by LeiHHHuang** [comment]
Thank you very much for your prompt reply, Soroush!
